### ISSUE TITLE
Think about arguments

### ISSUE THREAD

**Issue by nikymorg** [vibraniumforge/Baccarat#14]
https://github.com/vibraniumforge/Baccarat/blob/2f07e38b5886f372838dbf04c3f7c2b781432cc8/bacc.js#L246

You are passing in a lot of arguments like playerTotal which the function already has access to because it is defined in the same scope. Your function doesn't need arguments both ways.

**Comment by nikymorg** [comment]
In general think about what is the minimum arguments you need to run. Does the playerHand ever lose cards? If not, is it necessary to track the total number of cards the player holds separately. You also have several different variables to track the winning game state. Is there a way to make one variable, maybe an object that holds this information. It could have keys for who the winner is and if there are any special panda dragon things.

**Comment by vibraniumforge** [comment]
Removed all instances.
